# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('credentials', jsonfield.fields.JSONField(blank=True, null=True)),
                ('certificatePath', models.TextField(blank=True, max_length=100, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_first_name', models.TextField(blank=True, max_length=100, null=True)),
                ('customer_last_name', models.TextField(blank=True, max_length=100, null=True)),
                ('callback_url', models.TextField(blank=True, max_length=200, null=True)),
                ('complete_url', models.TextField(blank=True, max_length=200, null=True)),
                ('cancel_url', models.TextField(blank=True, max_length=200, null=True)),
                ('currency', models.TextField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, max_length=100, null=True)),
                ('order_amount', models.TextField(blank=True, max_length=100, null=True)),
                ('order_status', models.TextField(blank=True, max_length=100, null=True)),
                ('txn_ref_no', models.TextField(blank=True, max_length=100, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True, max_length=100, null=True)),
                ('response_code', models.TextField(blank=True, max_length=100, null=True)),
                ('response_message', models.TextField(blank=True, max_length=100, null=True)),
                ('response_status', models.TextField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.TextField(blank=True, max_length=20, null=True)),
                ('card_band', models.TextField(blank=True, max_length=100, null=True)),
                ('card_expiry_month', models.TextField(blank=True, max_length=100, null=True)),
                ('card_expiry_year', models.TextField(blank=True, max_length=100, null=True)),
                ('card_funding_method', models.TextField(blank=True, max_length=100, null=True)),
                ('card_name_on_card', models.TextField(blank=True, max_length=100, null=True)),
                ('card_number', models.TextField(blank=True, max_length=100, null=True)),
                ('card_scheme', models.TextField(blank=True, max_length=100, null=True)),
                ('fund_type', models.TextField(blank=True, max_length=100, null=True)),
                ('payment_status', models.TextField(blank=True, max_length=100, null=True)),
                ('total_authorized_amount', models.TextField(blank=True, max_length=100, null=True)),
                ('total_captured_amount', models.TextField(blank=True, max_length=100, null=True)),
                ('total_refunded_amount', models.TextField(blank=True, max_length=100, null=True)),
                ('stripe_publishable_key', models.TextField(blank=True, max_length=250, null=True)),
                ('stripe_secret_key', models.TextField(blank=True, max_length=250, null=True)),
                ('stripe_session_id', models.TextField(blank=True, max_length=250, null=True)),
                ('stripe_payment_intent', models.TextField(blank=True, max_length=250, null=True)),
                ('invoice_no', models.TextField(blank=True, max_length=200, null=True)),
                ('invoice_reference', models.TextField(blank=True, max_length=200, null=True)),
                ('invoice_url', models.TextField(blank=True, null=True)),
                ('response_description', models.TextField(blank=True, max_length=250, null=True)),
                ('request_status', models.TextField(blank=True, max_length=250, null=True)),
                ('fetch_order_type', models.TextField(blank=True, max_length=250, null=True)),
                ('click_2Pay', models.TextField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('connect_pay_id', models.TextField(blank=True, max_length=250, null=True)),
                ('order_number', models.TextField(blank=True, max_length=250, null=True)),
                ('is_fee_applied', models.TextField(blank=True, max_length=250, null=True)),
                ('connect_pay_fee', models.TextField(blank=True, max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransactions',
            index=models.Index(fields=['deleted'], name='paymentgate_deleted_398e09_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaycredentials',
            index=models.Index(fields=['deleted'], name='paymentgate_deleted_03b9ee_idx'),
        ),
    ]
