# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseDeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('device_token', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirebaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message_title', models.TextField(blank=True, null=True)),
                ('message_description', models.TextField(blank=True, null=True)),
                ('message_image_url', models.TextField(blank=True, null=True)),
                ('redirect_url', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirebaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_id', models.CharField(blank=True, max_length=200, null=True)),
                ('project_number', models.CharField(blank=True, max_length=200, null=True)),
                ('web_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('server_key', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=200, null=True)),
                ('vapid_key', models.CharField(blank=True, max_length=200, null=True)),
                ('credentials_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('auth_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_bucket', models.CharField(blank=True, max_length=200, null=True)),
                ('app_id', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirebaseNotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('firebase_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.firebasenotification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
