# Generated by Django 3.1.1 on 2022-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='hp_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='hp_social_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='hp_title',
            new_name='seo_description',
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
