# Generated by Django 3.1.1 on 2022-11-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20221114_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
