# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('feed_name', models.CharField(blank=True, max_length=200, null=True)),
                ('feed_type', models.CharField(blank=True, max_length=200, null=True)),
                ('export_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('export_variant', models.CharField(blank=True, max_length=200, null=True)),
                ('use_price', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('product_export', models.CharField(blank=True, max_length=200, null=True)),
                ('in_stock', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_collection_products', models.TextField(blank=True, null=True)),
                ('custom_collection_products_id', models.TextField(blank=True, null=True)),
                ('custom_label1', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_label2', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_label3', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_label4', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_collections', models.TextField(blank=True, null=True)),
                ('product_image', models.CharField(blank=True, max_length=200, null=True)),
                ('exclude_tags', models.TextField(blank=True, null=True)),
                ('feed_link', models.TextField(blank=True, null=True)),
                ('feed_status', models.CharField(blank=True, default='pending', max_length=200, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=200, null=True)),
                ('xml_output', models.TextField(blank=True, null=True)),
                ('no_of_products', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price_format', models.IntegerField(blank=True, default=2, null=True)),
                ('export_products', models.CharField(blank=True, max_length=200, null=True)),
                ('export_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
