# Generated by Django 3.1.1 on 2022-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220517_1607'),
        ('social_feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='custom_collection_products',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='custom_collection_products_id',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='feature_collections',
        ),
        migrations.AddField(
            model_name='feed',
            name='main_category',
            field=models.ManyToManyField(related_name='main_category_feed', to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='feed',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_category_feed', to='products.SubCategory'),
        ),
        migrations.AddField(
            model_name='feed',
            name='super_sub_category',
            field=models.ManyToManyField(related_name='super_sub_category_feed', to='products.SuperSubCategory'),
        ),
    ]
