# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=200, null=True)),
                ('criteria', models.CharField(blank=True, max_length=200, null=True)),
                ('y_criteria', models.CharField(blank=True, max_length=200, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=200, null=True)),
                ('value_type', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.DecimalField(decimal_places=0, default=0.0, max_digits=10)),
                ('check_minimum_purchase_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('x_minimum_no_products', models.IntegerField(default=0)),
                ('y_minimum_no_products', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_eligibility', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('no_limit', models.BooleanField(default=False)),
                ('show_both_price', models.BooleanField(default=False)),
                ('show_tag', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscountHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='discounthandle',
            index=models.Index(fields=['id', 'name'], name='discount_di_id_fd7cf4_idx'),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer',
            field=models.ManyToManyField(related_name='customer_discount', to='crm.Customer'),
        ),
    ]
