# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='main_category',
            field=models.ManyToManyField(related_name='main_category_discount', to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(related_name='product_discount', to='products.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product_group',
            field=models.ManyToManyField(related_name='product_group_discount', to='products.ProductGroup'),
        ),
        migrations.AddField(
            model_name='discount',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_category_discount', to='products.SubCategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='super_sub_category',
            field=models.ManyToManyField(related_name='super_sub_category_discount', to='products.SuperSubCategory'),
        ),
    ]
