# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('products', '0001_initial'),
        ('discount', '0002_auto_20220424_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_discount', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='discount',
            name='y_main_category',
            field=models.ManyToManyField(related_name='y_main_category_discount', to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='y_product',
            field=models.ManyToManyField(related_name='y_product_discount', to='products.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='y_product_group',
            field=models.ManyToManyField(related_name='y_product_group_discount', to='products.ProductGroup'),
        ),
        migrations.AddField(
            model_name='discount',
            name='y_sub_category',
            field=models.ManyToManyField(related_name='y_sub_category_discount', to='products.SubCategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='y_super_sub_category',
            field=models.ManyToManyField(related_name='y_super_sub_category_discount', to='products.SuperSubCategory'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['deleted'], name='discount_di_deleted_d4b024_idx'),
        ),
    ]
