# Generated by Django 3.1.1 on 2023-02-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20220424_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='apply_on_discounted_price',
            field=models.BooleanField(default=False),
        ),
    ]
