# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='userlastlogin',
            index=models.Index(fields=['id', 'user'], name='authenticat_id_1e09af_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted', 'id'], name='authenticat_deleted_366171_idx'),
        ),
    ]
