# Generated by Django 3.1.1 on 2022-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220424_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='featured_apps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='socialfeed',
            field=models.BooleanField(default=False),
        ),
    ]
