# Generated by Django 3.1.1 on 2022-11-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220429_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='blog',
            field=models.BooleanField(default=False),
        ),
    ]
