# Generated by Django 3.1.1 on 2023-02-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20230209_0219'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='rule',
            field=models.ManyToManyField(related_name='customer_rule', to='setting.Rule'),
        ),
    ]
