# Generated by Django 3.1.1 on 2023-02-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20230209_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltysetting',
            name='order_url',
        ),
        migrations.RemoveField(
            model_name='loyaltysetting',
            name='platform',
        ),
    ]
