# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zone', to='shipping.zone'),
        ),
        migrations.AddField(
            model_name='rule',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_shipping', to='shipping.shipping'),
        ),
        migrations.AddField(
            model_name='conditionalrate',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rate_rule', to='shipping.rule'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['title'], name='shipping_zo_title_eb25cf_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['deleted'], name='shipping_sh_deleted_86c501_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['shipping'], name='shipping_ru_shippin_8d2e94_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionalrate',
            index=models.Index(fields=['rule'], name='shipping_co_rule_id_83adb9_idx'),
        ),
    ]
