# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('shipping', '0001_initial'),
        ('products', '0001_initial'),
        ('order', '0002_auto_20220424_0248'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitems',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_order_customer', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='childorderlineitems',
            name='child_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_order_lineitem_order', to='order.childorder'),
        ),
        migrations.AddField(
            model_name='childorderlineitems',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childlineitem_shipping', to='shipping.shipping'),
        ),
        migrations.AddField(
            model_name='childorderlineitems',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_lineitem_variant', to='products.variant'),
        ),
        migrations.AddField(
            model_name='childorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childOrders_billingAddress', to='order.billingaddress'),
        ),
        migrations.AddField(
            model_name='childorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childOrders_order', to='order.order'),
        ),
        migrations.AddField(
            model_name='childorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childOrders_shippingAddress', to='order.shippingaddress'),
        ),
        migrations.AddField(
            model_name='childorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_customer', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress_checkout', to='order.checkout'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='draft_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress_draft_order', to='order.draftorder'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress_order', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['deleted'], name='order_shipp_deleted_c0b662_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order', 'child_order'], name='order_order_order_i_43acbc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_order_custome_df6711_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitems',
            index=models.Index(fields=['deleted'], name='order_linei_deleted_0069ad_idx'),
        ),
        migrations.AddIndex(
            model_name='draftorder',
            index=models.Index(fields=['id'], name='order_draft_id_4e71d6_idx'),
        ),
        migrations.AddIndex(
            model_name='childorderlineitems',
            index=models.Index(fields=['id'], name='order_child_id_be4b64_idx'),
        ),
        migrations.AddIndex(
            model_name='childorder',
            index=models.Index(fields=['id'], name='order_child_id_ad5416_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['deleted'], name='order_check_deleted_180d87_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['deleted'], name='order_billi_deleted_65e0d9_idx'),
        ),
    ]
