# Generated by Django 3.1.1 on 2022-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, to='products.Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_commission', to='vendor.commission'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='products.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product_tags', to='products.Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product'),
        ),
        migrations.AddField(
            model_name='media',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_media', to='products.brand'),
        ),
        migrations.AddField(
            model_name='media',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_media', to='products.collection'),
        ),
        migrations.AddField(
            model_name='media',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category_media', to='products.maincategory'),
        ),
        migrations.AddField(
            model_name='media',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='products.product'),
        ),
        migrations.AddField(
            model_name='media',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_media', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='media',
            name='super_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_sub_category_media', to='products.supersubcategory'),
        ),
        migrations.AddField(
            model_name='maincategorymetadata',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category_meta_data', to='products.maincategory'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['deleted', 'id', 'name'], name='products_ma_deleted_5689af_idx'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_inventory_history', to='products.variant'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product'),
        ),
        migrations.AddField(
            model_name='collectionrule',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_rules', to='products.collection'),
        ),
        migrations.AddField(
            model_name='collectionmetadata',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_meta_data', to='products.collection'),
        ),
        migrations.AddIndex(
            model_name='collectionhandle',
            index=models.Index(fields=['id', 'name'], name='products_co_id_663d1a_idx'),
        ),
        migrations.AddField(
            model_name='collection',
            name='main_category',
            field=models.ManyToManyField(blank=True, related_name='collection_main_category', to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='collection_sub_category', to='products.SubCategory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='super_sub_category',
            field=models.ManyToManyField(blank=True, related_name='collection_super_sub_category', to='products.SuperSubCategory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_vendor', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='categoryhandle',
            index=models.Index(fields=['id', 'name'], name='products_ca_id_04cb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='brandhandle',
            index=models.Index(fields=['id', 'name'], name='products_br_id_aa525d_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['deleted', 'id', 'name'], name='products_br_deleted_e455f6_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['deleted', 'id', 'title', 'product'], name='products_va_deleted_cf5d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='supersubcategory',
            index=models.Index(fields=['deleted', 'id', 'name', 'sub_category'], name='products_su_deleted_d37c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategorycondition',
            index=models.Index(fields=['id', 'sub_category'], name='products_su_id_dad47a_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['deleted', 'id', 'name', 'main_category'], name='products_su_deleted_10c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['deleted', 'id'], name='products_pr_deleted_9f4008_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted', 'id', 'product_group'], name='products_pr_deleted_31402c_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['deleted', 'id', 'product'], name='products_op_deleted_46729d_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['id', 'brand', 'collection', 'product', 'main_category', 'sub_category', 'super_sub_category'], name='products_me_id_d7c5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['id'], name='products_in_id_a6d656_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['deleted', 'id', 'product'], name='products_fe_deleted_297ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrule',
            index=models.Index(fields=['id', 'collection'], name='products_co_id_17b813_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['deleted', 'id', 'title', 'vendor'], name='products_co_deleted_25088c_idx'),
        ),
    ]
