# Generated by Django 3.1.1 on 2022-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_media_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variant',
            name='old_inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
